In [32]:
import numpy as np

In [33]:
arr2= np.array([[1,2,3,4,5],[6,7,8,9,10]])

In [34]:
arr2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [37]:
np.asarray([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [38]:
list1= [5,6,7,"uu","ghr"]

In [49]:
arr1=np.asarray(list1)

In [40]:
np.ceil(1.5)

2.0

In [44]:
np.cos(3.141592653589793)

-1.0

In [43]:
np.pi

3.141592653589793

In [55]:
arr3=np.append(arr1,22)

In [59]:
arr4=np.insert(arr3, -4,666)

In [60]:
arr4

array(['5', '6', '666', '7', 'uu', 'ghr', '22'], dtype='<U11')

In [62]:
np.insert(arr2,1,[66,77],1)

array([[ 1, 66,  2,  3,  4,  5],
       [ 6, 77,  7,  8,  9, 10]])

In [69]:
arr33= np.ndarray([2,4])

In [71]:
arr33

array([[0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000],
       [0.00000000e+000, 8.35959073e-321, 7.23168526e-308,
        3.11523242e-307]])

In [72]:
np.ndarray([44,1])

array([[6.13683785e-071],
       [9.36374059e-076],
       [1.43623279e+161],
       [9.02133905e+217],
       [5.92863223e-114],
       [9.02133865e+217],
       [9.02133843e+217],
       [1.09363961e-094],
       [6.13657267e-071],
       [9.36374587e-076],
       [1.05901196e+218],
       [7.52132850e+130],
       [7.53215929e+130],
       [9.29602247e+242],
       [7.60446783e+130],
       [7.53432543e+130],
       [6.61020264e-062],
       [9.02133645e+217],
       [9.31734083e+242],
       [7.60446783e+130],
       [7.53107621e+130],
       [4.67485107e-062],
       [6.13683785e-071],
       [9.02133865e+217],
       [6.13649668e-071],
       [6.79427156e+247],
       [7.54946406e+130],
       [6.55490914e-260],
       [1.03063392e-113],
       [2.00008958e+174],
       [5.38214630e+228],
       [1.90857244e+185],
       [8.02678501e-095],
       [1.15939498e-012],
       [6.01347002e-154],
       [5.03507107e+175],
       [8.02678501e-095],
       [7.93885765e+068],
       [1.23

In [73]:
np.mean(np.ndarray([44,1]))

4.790866799273012e+246

In [76]:
np.var(np.ndarray([44,1]))**0.5

inf

In [79]:
arr33.shape

(2, 4)

In [86]:
list1.append(888)

In [87]:
list2=list1.copy()

In [90]:
list2.pop()

888

In [92]:
list2

[5, 6, 7, 'uu', 'ghr', 888]

In [93]:
arr4=np.asarray(list2).reshape(3,2)

In [94]:
arr4

array([['5', '6'],
       ['7', 'uu'],
       ['ghr', '888']], dtype='<U11')

In [95]:
np.insert(arr4,2,["77","uu","kk"],1)

array([['5', '6', '77'],
       ['7', 'uu', 'uu'],
       ['ghr', '888', 'kk']], dtype='<U11')

In [96]:
arr4

array([['5', '6'],
       ['7', 'uu'],
       ['ghr', '888']], dtype='<U11')

In [101]:
arr5=np.append(arr4,[[1,3]],0)

In [102]:
arr5

array([['5', '6'],
       ['7', 'uu'],
       ['ghr', '888'],
       ['1', '3']], dtype='<U11')

In [104]:
arr5[1,1]

'uu'

In [116]:
def access(array, row, col):
    if row<=len(array)-1 and len(array[0])-1:
        return(array[row][col])
    else:
        print("Enter correct indices")

In [106]:
access(arr5,1,1)

'uu'

In [107]:
access(arr5,2,1)

'888'

In [110]:
type(arr2[0,1])

numpy.int32

In [112]:
arr2.shape

(2, 5)

In [113]:
arr2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [114]:
np.mean(arr2,1)

array([3., 8.])

In [115]:
np.var(arr2,1)

array([2., 2.])

In [117]:
for i in range(len(arr5)):
    for j in range(len(arr5[0])):
        if i>j:
            print(arr5[i,j])

7
ghr
888
1
3


### Order of O(mn)